### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by lattice0** [stormbreaker-project/kernel_poco_citrus#3]
Hello my friend, I see that you got this kernel working on the Poco M3. May you kindly help me figuring out what I'm doing wrong? Because my kernel won't boot.

I'm trying to compile this kernel https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/lime-q-oss for my Poco M3

I did:

```
export ARCH=arm64 && export SUBARCH=arm64
export CROSS_COMPILE=/opt/aosp_prebuilts/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export DTC_EXT="/opt/google_misc/misc/linux-x86/dtc/dtc"
make ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- vendor/citrus-perf_defconfig
make ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- EXTRA_CFLAGS="-I $PWD/techpack/display/pll/ -I $PWD/techpack/camera/drivers/cam_sensor_module/cam_cci/  -I $PWD/techpack/camera/drivers/cam_req_mgr -DSDCARDFS_VERSION= -I $PWD/" -j$(nproc --all) 2>&1 | tee kernel.log
```
and unpacked/repacked boot.img with

```
unpackbootimg -i boot.img -o boot_img_unpacked

mkbootimg --kernel "$SCRIPT_DIR/devices/$DEVICE/kernel/k/arch/arm64/boot/Image.gz" \
    --ramdisk boot.img-ramdisk \
    --dtb boot.img-dtb \
    --cmdline "$(< boot.img-cmdline)" \
    --base "$(< boot.img-base)" \
    --kernel_offset "$(< boot.img-kernel_offset)" \
    --ramdisk_offset "$(< boot.img-ramdisk_offset)" \
    --tags_offset "$(< boot.img-tags_offset)" \
    --dtb_offset "$(< boot.img-dtb_offset)" \
    --os_version "$(< boot.img-os_version)" \
    --os_patch_level "$(< boot.img-os_patch_level)" \
    --pagesize "$(< boot.img-pagesize)" \
    --header_version "$(< boot.img-header_version)" \
    --hashtype "$(< boot.img-hashtype)" \
    --board "$(< boot.img-board)" \
    -o ../boot.img
```

but it won't boot. I get stuck on the Poco M3 screen. I tried unpacking/repacking the original boot.img with the original kernel just to see if I was repacking wrong but it worked, so my repack is working.

I think the issue might be with dtbo inside the kernel, because my compiled kernel has 28mb vs 32mb from the original one. It's worth noting that the original one is for Android 11 and the one I compiled is for Android 10 but I doubt this is the problem because both are 4.19.x and usually one kernel works over 2 Android versions.

I also tried adding `CONFIG_BUILD_ARM64_DT_OVERLAY=y` to

`vendor/citrus-perf_defconfig` but it also won't boot.

**Comment by danascape** [comment]
its not the matter anymore that android 10 kernels will work on 11 since while doing the bringup of my oneplus device, I was not able to bootup 10 kernel on 11 OS because of some issues with encryption and stuff.

**Comment by lattice0** [comment]
@danascape but did you get up to the animation part at least? I fell I should be able to at least see the animation. It looks like the kernel is completely broken. Do you have any tips debugging this?

**Comment by danascape** [comment]
check pstore

**Comment by lattice0** [comment]
@danascape the problem is that for checking pstore I need root, but there's no official TWRP for the Poco M3

**Comment by danascape** [comment]
uh, you can use unofficials

**Comment by danascape** [comment]
or AOSP recovery

**Comment by lattice0** [comment]
I tried all clang prebuilts from AOSP 10 and 11, some of them make the phone boot loop, and some simply make it get stuck at the boot logo forever. I rooted the phone with magisk and then tried to check pstore, last_kmsg, etc, there was nothing (and yes, xiaomi's official kernel has PSTORE activated). Also, there's no support for `fastboot oem enable uart` so I don't know what I can do anymore to make this work.

May I know where this specific kernel comes from? Is it from codeaurora? If so, how do you know which modifications needs to be done for it to work on the Poco M3? I want to get into this field but it's really hard to debug. I extracted qualcomm's bootloader and found some hidden fastboot commands like `fastboot oem lkmsg` and `fastboot oem lpmsg`:

```
fastboot oem lpmsg
FAILED (remote: 'Failed to get lpmsg')
fastboot: error: Command failed
```

I'm trying to analyze on Cutter the logic behind this, and I think that lpmsg means "last pstore message" but anyways, I couldn't get anything from it. 

Could someone give me a hand? I'd appreciate very much :)

**Comment by danascape** [comment]
do not expect uart to be this easy on a xiaomi.
the initial kernel source was released by OEM (xiaomi) at https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/lime-q-oss

**Comment by lattice0** [comment]
@danascape yes I'm using this source but this kernel `stormbreaker-project/kernel_poco_citrus` does not share the same history as `[Xiaomi_Kernel_OpenSource/tree/lime-q-oss](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/lime-q-oss)`

Latest Xiaomi commit: 

https://github.com/stormbreaker-project/kernel_poco_citrus/commits/main?after=0399cad3bd0bdcce0070259236a6e89ab2dfae7c+174&branch=main

which is not present in `stormbreaker-project/kernel_poco_citrus` commits, so it looks like they are different kernels.

And yes, I'm not optimistic about UART, but maybe `fastboot oem lkmsg`

**Comment by danascape** [comment]
okay so @starlight5234 just mentioned that the issue is that the dtbo from miui kernel does not match the stock dtbo that is why you are stuck. https://github.com/stormbreaker-project/kernel_poco_citrus/commit/61598910db1dbe34aea29ec5a7bc15d29a001694

**Comment by lattice0** [comment]
I don't get it. Isn't the dtbo already in boot.img? I'm repacking only the kernel from inside the boot.img, so the dtbo is in a different file that I do not touch.

-------- Mensagem Original --------
Ativo 27 de mar. de 2022 09:55, Saalim Quadri escreveu:

**Comment by danascape** [comment]
No it's not

**Comment by lattice0** [comment]
Ok I did 

`CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE=y`

on the citrus-perf_defconfig because otherwise it won't even build the Image-gz.dtb. I made those patches also, but the device still boot loops. I tried both with Image-gz.dtb and Image.gz.

Just to confirm: I should repack with Image-gz.dtb, right? 

And very important: **which clang do you guys use**? I tried all clangs from Android 10 and 11 and some of them bootloops, and some never reboot, but none arrive at the boot animation.

Also, I don't get why I need to insert the dtb inside the kernel. If you inspect the kernel with https://github.com/PabloCastellano/extract-dtb then you'll see that inside the kernel there is no device tree, only on boot.img in the dtb file

**Comment by qwertyuiii-code** [comment]
Where is defconfig for juice or chime or citrus defconfig support lemon or lime?

**Comment by starlight5234** [comment]
> Where is defconfig for juice or chime or citrus defconfig support lemon or lime?

citrus support lime
